"""empty message

Revision ID: 4fd96eefc9b0
Revises: 9f08b04ddced
Create Date: 2022-08-06 12:56:39.681991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd96eefc9b0'
down_revision = '9f08b04ddced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('Venue_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], )
    )
    op.drop_table('show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], name='show_Venue_id_fkey'),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='show_artist_id_fkey')
    )
    op.drop_table('Show')
    # ### end Alembic commands ###
