"""empty message

Revision ID: 7363c5357a93
Revises: b56734469705
Create Date: 2022-08-03 13:41:08.512977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7363c5357a93'
down_revision = 'b56734469705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('Venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###
