"""empty message

Revision ID: 9f08b04ddced
Revises: 8c46ecad6644
Create Date: 2022-08-05 20:12:01.597381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f08b04ddced'
down_revision = '8c46ecad6644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('Venue_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###
