"""empty message

Revision ID: a5922311774f
Revises: 7363c5357a93
Create Date: 2022-08-03 13:45:45.293586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5922311774f'
down_revision = '7363c5357a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'time')
    # ### end Alembic commands ###
