"""empty message

Revision ID: b56734469705
Revises: bf1dd3a8a395
Create Date: 2022-08-03 12:40:08.996959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56734469705'
down_revision = 'bf1dd3a8a395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('genre', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('desc', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genre', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('desc', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'talent')
    op.drop_column('Venue', 'desc')
    op.drop_column('Venue', 'genre')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Artist', 'talent')
    op.drop_column('Artist', 'desc')
    op.drop_column('Artist', 'genre')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
